export const majors = [
  "N/A",
  "Accounting",
  "Agricultural and Resource Economics",
  "American Studies",
  "Animal and Avian Sciences",
  "Anthropology",
  "Applied Mathematics and Scientific Computation",
  "Arabic Studies",
  "Art History",
  "Astronomy",
  "Atmospheric and Oceanic Science",
  "Biochemistry",
  "Biological Sciences",
  "Chemistry",
  "Chinese Studies",
  "Cinema and Media Studies",
  "Civil Engineering",
  "Communication",
  "Computer Science",
  "Criminology and Criminal Justice",
  "Economics",
  "Electrical Engineering",
  "English Language and Literature",
  "Environmental Science and Policy",
  "Finance",
  "Geography",
  "Geology",
  "Government and Politics",
  "History",
  "Information Science",
  "International Business",
  "Journalism",
  "Linguistics",
  "Management",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Neuroscience",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health Science",
  "Sociology",
  "Spanish Language and Literature",
  "Statistics",
  "Theatre",
  "Women's Studies",
];
export const minors = [
  "N/A",
  "African American Studies",
  "Arabic Studies",
  "Art History",
  "Asian American Studies",
  "Black Women’s Studies",
  "Business Analytics",
  "Business Administration",
  "Chinese Studies",
  "Classics",
  "Communication",
  "Computer Science",
  "Creative Writing",
  "Criminology and Criminal Justice",
  "Dance",
  "Digital Studies",
  "East Asian Studies",
  "Economics",
  "Education",
  "English",
  "Environmental Science and Policy",
  "Film Studies",
  "French Studies",
  "Geographic Information Science",
  "German Studies",
  "Global Poverty",
  "History",
  "Human Development",
  "Information Science",
  "International Business",
  "Jewish Studies",
  "Journalism",
  "Latin American Studies",
  "Linguistics",
  "Management",
  "Marketing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Sociology",
  "Spanish Studies",
  "Statistics",
  "Theatre",
  "Women’s Studies",
];
export const creditHours = ["N/A", "1", "2", "3", "4"];
