name: Build and submit

on:
  push:
    branches: ["android"]

jobs:
  build_android:
    name: Build Android app
    type: build
    params:
      platform: android
      profile: production
  submit_android:
    name: Submit Android
    type: submit
    needs: [build_android]
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
